### ISSUE TITLE
In [CMD-LINE]:1: Error opening configuration file: /vol/config/openvpn.conf

### ISSUE THREAD

**Issue by tserversbfs** [PHLAK/docker-openvpn#5]
I am just trying your image and ran into a problem... I hope you can help.

    docker run -d \
        --name openvpn-client \
        --privileged \
        --cap-add=NET_ADMIN \
        --device /dev/net/tun \
        -v ${HOME}/srv_cfg/openvpn/client:/vol/config \
        --dns 1.1.1.1 \
        --dns 1.0.0.1 \
        -p 12000:12000 \
        --restart unless-stopped \
        phlak/openvpn

docker stop openvpn-client

docker start -i openvpn-client 
Options error: In [CMD-LINE]:1: Error opening configuration file: /vol/config/openvpn.conf
Use --help for more information.

docker exec -i openvpn-client /bin/bash
Error response from daemon: Container 5309f5e41c24afedfca09d321582649cbc93646361a23d26e73f715361a8fe4c is restarting, wait until the container is running

in my config folder I have:
openvpn.conf  update-resolv-conf  user_pass.txt

These 3 files are supplied by my VPN service. 

openvpn.conf: 
remote *removed* 1196 udp
remote *removed* 1196 udp
fragment 1300
explicit-exit-notify 3
auth-user-pass user_pass.txt
up 'update-resolv-conf'
down 'update-resolv-conf'
auth RSA-SHA512
dev tap
server-poll-timeout 20
client
nobind
resolv-retry infinite
auth-retry nointeract
persist-key
persist-tun
cipher AES-256-CBC
mute-replay-warnings
comp-lzo
verb 3
mute 20
remote-cert-tls server
route-method exe
route-delay 2
script-security 3
reneg-sec 0
<ca>
-----BEGIN CERTIFICATE-----
*removed*
-----END CERTIFICATE-----
</ca>

**Comment by PHLAK** [comment]
First, double check that you have the correct path. Otherwise, maybe a permissions error?

Do the docker logs show any additional information?

    docker logs <your_container_name>

**Comment by tserversbfs** [comment]
Yup. You got it. I put all my *.opvn files in ./openvpn/client and instinctively put the 3 need config files in ./openvpn. Reading your docs with my brain in neutral. 

docker logs didnt provide any more useful information. just repeated the error that i got from "-i".

Thank you. 

Now I am getting this:
ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

but I have not looked into the cause yet as it just happened. 

I do have two question if you do not mind answering it. After I start openvpn and attach containers to it with "--net container:openvpn-client". If I start the openvpn container do I need to restart the attached container? Or will they reconnect?

If I /bin/bash into the container is there a command available to restart openvpn without restarting the container?

Thank you.

**Comment by tserversbfs** [comment]
https://discuss.linuxcontainers.org/t/openvpn-error-cannot-open-tun-tap-dev-dev-net-tun-no-such-file-or-directory-errno-2-solved/1614

ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

$ mkdir -p /dev/net
$ mknod /dev/net/tun c 10 200

This worked! 

Steps:
- docker run -t -i --entrypoint sh [...]
- apk add bash
- mkdir -p /dev/net
- mknod /dev/net/tun c 10 200
- openvpn --config [...]

**Comment by tserversbfs** [comment]
This worked for me locally, then forked it and tried from github and it failed. Will try again later.
"FROM alpine:3.12.1
LABEL maintainer="Chris Kankiewicz <Chris@ChrisKankiewicz.com>"

-# Define OpenVPN version
ARG OVPN_VERSION=2.4.9-r0

-# Create OpenVPN conf directory
RUN mkdir -p /vol/config
RUN mkdir -p /dev/net
CMD [ "sh", "-c", "mknod /dev/net/tun c 10 200" ]

-# Install OpenVPN
RUN apk add --update openvpn=${OVPN_VERSION} && rm -rf /var/cache/apk/*

-# Set working directory
WORKDIR /vol/config

-# Default entrypoint and run command
ENTRYPOINT ["openvpn", "--config", "/vol/config/openvpn.conf", "--verb", "3", "--remap-usr1", "SIGTERM"]
CMD ["--script-security", "2", "--up", "/etc/openvpn/up.sh", "--down", "/etc/openvpn/down.sh"]"

Sorry about the -# for the comment lines, but I couldn't turn off formatting. *shrugs*
